package tasks;


/**
* tasks/AbstractTask.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corba.idl
* Sobota, 2021, apríla 3 17:18:02 CEST
*/

public interface AbstractTask extends org.omg.CORBA.portable.IDLEntity
{
  String info ();
  tasks.AbstractTask next () throws tasks.TaskException;
} // interface AbstractTask
