package tasks;

/**
* tasks/AbstractTaskHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corba.idl
* Sobota, 2021, apríla 3 17:18:02 CEST
*/

public final class AbstractTaskHolder implements org.omg.CORBA.portable.Streamable
{
  public tasks.AbstractTask value = null;

  public AbstractTaskHolder ()
  {
  }

  public AbstractTaskHolder (tasks.AbstractTask initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = tasks.AbstractTaskHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    tasks.AbstractTaskHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return tasks.AbstractTaskHelper.type ();
  }

}
