package tasks;


/**
* tasks/AdderTaskOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corba.idl
* Nedeľa, 2021, apríla 4 0:39:56 CEST
*/

public interface AdderTaskOperations  extends tasks.AbstractTask
{
  int a ();
  float b ();
  double result ();
  void result (double newResult);
} // interface AdderTaskOperations
