package tasks;

/**
* tasks/AdderTaskHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corba.idl
* Nedeľa, 2021, apríla 4 0:39:56 CEST
*/

public final class AdderTaskHolder implements org.omg.CORBA.portable.Streamable
{
  public tasks.AdderTask value = null;

  public AdderTaskHolder ()
  {
  }

  public AdderTaskHolder (tasks.AdderTask initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = tasks.AdderTaskHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    tasks.AdderTaskHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return tasks.AdderTaskHelper.type ();
  }

}
