package tasks;


/**
* tasks/AdderTask.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corba.idl
* Nedeľa, 2021, apríla 4 0:39:56 CEST
*/

public interface AdderTask extends AdderTaskOperations, tasks.AbstractTask, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface AdderTask
