package tasks;


/**
* tasks/FlipLineTaskOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corba.idl
* Pondelok, 2021, apríla 5 11:43:35 CEST
*/

public interface FlipLineTaskOperations  extends tasks.AbstractTask
{
  void update (tasks.Point[] flippedPolyLine, org.omg.CORBA.IntHolder lengthDifference);
} // interface FlipLineTaskOperations
