package tasks;


/**
* tasks/FlipLineTask.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corba.idl
* Pondelok, 2021, apríla 5 11:43:35 CEST
*/

public interface FlipLineTask extends FlipLineTaskOperations, tasks.AbstractTask, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface FlipLineTask
