package tasks;


/**
* tasks/InitialTaskOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corba.idl
* Sobota, 2021, apríla 3 17:18:02 CEST
*/

public interface InitialTaskOperations 
{
  tasks.AbstractTask init (String email) throws tasks.TaskException;
} // interface InitialTaskOperations
