package tasks;


/**
* tasks/MatrixTaskOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corba.idl
* Pondelok, 2021, apríla 5 11:12:09 CEST
*/

public interface MatrixTaskOperations  extends tasks.AbstractTask
{
  int getMatrixItem (int row, int col) throws tasks.TaskException;
  void sendResult (int matrixDeterminant);
} // interface MatrixTaskOperations
