package tasks;


/**
* tasks/MatrixTask.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corba.idl
* Pondelok, 2021, apríla 5 11:12:09 CEST
*/

public interface MatrixTask extends MatrixTaskOperations, tasks.AbstractTask, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
  public static final int matrixSize = (int)(3);
} // interface MatrixTask
