package tasks;


/**
* tasks/PolygonTask.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corba.idl
* Pondelok, 2021, apríla 5 11:31:35 CEST
*/

public interface PolygonTask extends PolygonTaskOperations, tasks.AbstractTask, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface PolygonTask
