package tasks;


/**
* tasks/PolygonTaskOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corba.idl
* Pondelok, 2021, apríla 5 11:31:35 CEST
*/

public interface PolygonTaskOperations  extends tasks.AbstractTask
{
  tasks.Point[] getPolyLine ();
  void sendResult (float polyLineLength);
} // interface PolygonTaskOperations
