package tasks;


/**
* tasks/SimpleTaskOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corba.idl
* Sobota, 2021, apríla 3 17:18:02 CEST
*/

public interface SimpleTaskOperations  extends tasks.AbstractTask
{
  boolean isReady ();
} // interface SimpleTaskOperations
