package tasks;


/**
* tasks/SimpleTask.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corba.idl
* Sobota, 2021, apríla 3 17:18:02 CEST
*/

public interface SimpleTask extends SimpleTaskOperations, tasks.AbstractTask, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface SimpleTask
